### ISSUE TITLE
Signed Headers not honored

### ISSUE THREAD

**Issue by rbeede** [anvilventures/aws-sigv4#11]
If I specify Signed Headers with an exact list of what I want the plugin is till adding other x-amx-* that is sees. Even if I want to exclude some headers they are still added.

I tried specifying the headers I wanted in the SigV4 burp tab UI under Signed Headers (Specify comma-separated...) with no change.

I want to exclude some x-amz- headers but cannot with Sigv4.

**Comment by UserExistsError** [comment]
There is no functionality in this extension to exclude any headers from the signature. The UI only allows you to add headers in addition to the ones chosen here: 
https://github.com/anvilventures/aws-sigv4/blob/314d40a1ebbb4e7af3ed9dbb8837ad04d1c4c23c/src/main/java/burp/BurpExtender.java#L1396

You can try modifying the code to remove headers but the AWS SDK may complain since it has a say on which headers are required and will add it's own. You can try that here: https://github.com/anvilventures/aws-sigv4/blob/314d40a1ebbb4e7af3ed9dbb8837ad04d1c4c23c/src/main/java/burp/BurpExtender.java#L1473 

If you want more control over which headers to sign, you might try using this old branch which computes the signature without the AWS SDK and allows more control. Using this would still require modification for adding the ability to exclude headers.
https://github.com/anvilventures/aws-sigv4/tree/legacy.

In the future it might be nice to add a feature to select between the AWS SDK signer and a custom signer which gives the user more control over the signed headers.

**Comment by UserExistsError** [comment]
Also, you might just try using Burp's builtin proxy settings under Proxy -> Options -> Match and Replace to remove unwanted headers.
