### ISSUE TITLE
Bug: Extension does not work in combination with Logger++

### ISSUE THREAD

**Issue by KwnyPwny** [anvilventures/aws-sigv4#9]
Hi,

thanks for your extension. I think it is super useful.
However, I recognized that in combination with Logger++ the extension gives erroneous results.
Logger++ shows timeouts for every request that was manipulated by the extension although the requests get answered by the web server. This is especially unfavorable in combination with the Burp Scanner, because the responses to sent requests cannot be viewed because of the alleged timeouts.
Other extensions that are manipulating request before transmission manage to show the final request and response within Logger++.

Best regards
Kwnypwny

**Comment by UserExistsError** [comment]
It looks like Logger++ uses the [comment field](https://github.com/PortSwigger/logger-plus-plus/blob/aa45f407ecb4bf710ee8feebaae994da60714e57/src/main/java/com/nccgroup/loggerplusplus/logview/processor/LogProcessor.java#L96) to store some state. The SigV4 extension overwrites the comment with the signing profile so Logger++ can no longer track the response.

I think the fix is to change [this](https://github.com/anvilventures/aws-sigv4/blob/314d40a1ebbb4e7af3ed9dbb8837ad04d1c4c23c/src/main/java/burp/BurpExtender.java#L1683) line to append to the comment. For now, you can just comment out that `setComment` line and it will work for you.

**Comment by UserExistsError** [comment]
Added a fix in https://github.com/anvilventures/aws-sigv4/commit/d32ba8b5e3ad5fccc26744babe2e59670388b6cc.
